### ISSUE TITLE
names for palette?

### ISSUE THREAD

**Issue by joelnitta** [malcolmbarrett/ggokabeito#2]
Thanks for this package! Very excited to see my fav palette get its own package :)

I think it would be useful if the vector produced by `palette_okabe_ito()` had names evocative of each color. That way it would be easy to manually select colors one wants to use, e.g., `palette_okabe_ito()[c("green", "orange")]` etc.

ggokabeito v.0.1.0

**Comment by malcolmbarrett** [comment]
Thanks for the suggestion! #3 will allow you to do so like this:

``` r
library(ggokabeito)
palette_okabe_ito(order = c("bluishgreen", "yellow", "blue"))
#> [1] "#009E73" "#F0E442" "#0072B2"
```

<sup>Created on 2022-02-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by joelnitta** [comment]
Awesome, thanks!
